version: '3'
services:

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: localhost:5000/frontend-image
    restart: unless-stopped
    depends_on:
      - worker
    hostname: frontend
    container_name: recipe.frontend
    ports:
      - "80:80"
    volumes:
      - ./config/config.json:/config/config.json
  
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: localhost:5000/worker-image
    restart: unless-stopped
    depends_on:
      - database
    hostname: worker-service
    container_name: recipe.worker
    volumes:
      - ./config/config.json:/config/config.json
      - ./worker/models:/models
    # ports:
    #   - "8000:8000"
  
  database:
    image: redis/redis-stack:latest
    restart: unless-stopped
    hostname: database-service
    container_name: recipe.database
    volumes:
      - ./shared_database/data/redis:/data
    # ports:
    #   - "6379:6379"
    #   - "8001:8001"

# /c/Users/ollie/OneDrive/Documents/GitHub/Recipe-Finder/