version: '3'
services:

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: frontend-image
    restart: unless-stopped
    depends_on:
      - worker
    hostname: frontend
    container_name: recipe.frontend
    ports:
      - "80:80"
    volumes:
      - .config.json:/config/.config.json
  
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: worker-image
    restart: unless-stopped
    depends_on:
      - database
    hostname: worker-service
    container_name: recipe.worker
    volumes:
      - .config.json:/config/.config.json
      - ./worker/models:/models
  
  database:
    image: redis/redis-stack:latest
    restart: unless-stopped
    hostname: database-service
    container_name: recipe.database
    volumes:
      - ./shared_database/data/redis:/data