# Recipe finder
# --------------------
# - Deployment to launch one container of recipe finder app.
# 
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - name: http
      port: 7000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  config.json: |
    {
        "frontend":{
            "worker_url":"http://worker-service:7000"
        },
        "worker":{
            "redis_url":"redis://database-service:6379",
            "redis_index":"recipes"
        }
    }
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "C:\\Users\\ollie\\OneDrive\\Documents\\GitHub\\Recipe-Finder\\shared_database\\data\\redis"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "C:\\Users\\ollie\\OneDrive\\Documents\\GitHub\\Recipe-Finder\\worker\\models"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: localhost:5000/frontend-image:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /config
              name: config-volume
          ports:
            - containerPort: 80
      volumes:
        - name: config-volume
          configMap:
            name: config-map
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: localhost:5000/worker-image:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /config
              name: config-volume
            - mountPath: /models
              name: models-volume
          ports:
            - containerPort: 7000
      volumes:
        - name: config-volume
          configMap:
            name: config-map
        - name: models-volume
          persistentVolumeClaim:
            claimName: model-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: redis/redis-stack:latest
          volumeMounts:
            - mountPath: /data
              name: data-volume
          ports:
            - containerPort: 6379
      volumes:
        - name: data-volume
          hostPath:
          persistentVolumeClaim:
            claimName: data-pvc